### ISSUE TITLE
Use quasiquotation instead of doublequoting

### ISSUE THREAD

**Issue by nfultz** [flynnzac/genvar#2]
I would recommend using rlang quasiquotations or formulas for the `gen` function, to keep down the number of quotes per command.

**Comment by flynnzac** [comment]
That makes sense.  I will add quasiquotation support.

**Comment by flynnzac** [comment]
`dev` branch now has this for `gen`.  I will add to the other functions as well so that `collapse(sum(x), y)`, etc, works too.  Good call.

**Comment by flynnzac** [comment]
All other functions that can use quasiquote-type syntax have been updated as best I can tell.  Merged into master.
